apiVersion: v1
kind: Namespace
metadata:
  name: prod-api
  labels:
    environment: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-auth
  labels:
    environment: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-image
  labels:
    environment: production 

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-monitoring
  labels:
    environment: production
